permalink: /:year/:month/:day/:title
exclude: [go, .scripts, README.md, .gitignore]
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
encoding: utf-8
github: [metadata]
repository: itruett/isaac.truett.info
social:
  name: Isaac Truett
  links:
    - https://plus.google.com/+IsaacTruett
    - https://www.linkedin.com/in/isaac-truett/
    - https://github.com/itruett/
    - https://stackoverflow.com/users/374293/isaac-truett
sass:
    style: compressed
