#! /usr/bin/env bash
#
# Starts the built-in Jekyll development server

_serve() {
	local IP=$(ip -f inet addr show eth0 | sed -n -e 's/^    inet \(.*\)\/.*$/\1/p')
	bundle exec jekyll serve --host=$IP ${_GO_CMD_ARGV}
}

_serve "$@"
